# Generated by Django 2.2.5 on 2019-09-18 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='タイトル')),
                ('body', models.TextField(blank=True, max_length=1000, null=True, verbose_name='本文')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name='公開状態')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='削除日時')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='本文'),
        ),
        migrations.CreateModel(
            name='UserPageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='削除日時')),
                ('page_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bamboo.PageComment', verbose_name='ページコメント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='PagePageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='削除日時')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bamboo.Page', verbose_name='ページ')),
                ('page_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bamboo.PageComment', verbose_name='ページコメント')),
            ],
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='pages',
            field=models.ManyToManyField(through='bamboo.PagePageComment', to='bamboo.Page'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='users',
            field=models.ManyToManyField(through='bamboo.UserPageComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='page_comments',
            field=models.ManyToManyField(through='bamboo.PagePageComment', to='bamboo.PageComment'),
        ),
    ]
